import { MantineTheme, MantineThemeOverride } from "@mantine/core";

const customMantineTheme = {
  colorScheme: "light",
  colors: {
    "tungsten-main": [
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
      "#0e2037",
    ],
    "button-blue": [
      "#e7f4fe",
      "#b7defb",
      "#87c8f8",
      "#56b2f5",
      "#269cf2",
      "#0075CA",
      "#0a66a9",
      "#074978",
      "#042c48",
      "#010f18",
    ],
    "grey-manual": [
      "#F8F9FA",
      "#F5F5F5",
      "#bfbfbf",
      "#a6a6a6",
      "#F7F8FA",
      "#787777",
      "#595959",
      "#404040",
      "#262626",
      "#120b0d",
    ],
    "light-grey": [
      "#ececef",
      "#d5d5d7",
      "#bbbbbe",
      "#9f9fa5",
      "#83838d",
      "#6a6a74",
      "#53535a",
      "#3b3b3f",
      "#232326",
      "#0c0c0e",
    ],
    "dark-grey": [
      "#fbf0f2",
      "#dcd8d9",
      "#bfbfbf",
      "#a6a6a6",
      "#8c8c8c",
      "#737373",
      "#595959",
      "#444444",
      "#282626",
      "#150a0d",
    ],
    "border-grey": [
      "#f8f0f2",
      "#d1d1d1",
      "#bfbfbf",
      "#a6a6a6",
      "#8c8c8c",
      "#737373",
      "#595959",
      "#404040",
      "#262626",
      "#120b0d",
    ],
    "blue-manual": [
      "#dcf6ff",
      "#aee0ff",
      "#7ec9ff",
      "#4db4ff",
      "#229efe",
      "#0d85e5",
      "#0075ca",
      "#004a81",
      "#002c50",
      "#001020",
    ],
    "violet-manual": [
      "#fcebfa",
      "#e7cce2",
      "#d3accd",
      "#C492BC",
      "#ad6ba2",
      "#945289",
      "#743f6b",
      "#542d4e",
      "#341a2f",
      "#170613",
    ],
    "run-green": [
      "#dfffdf",
      "#b0ffb0",
      "#7fff7f",
      "#4dff4d",
      "#0be606",
      "#00CB00",
      "#00b300",
      "#008000",
      "#004d00",
      "#001b00",
    ],
    "white-manual": [
      "#ffffff",
      "#f2f2f2",
      "#bfbfbf",
      "#a6a6a6",
      "#8c8c8c",
      "#737373",
      "#595959",
      "#404040",
      "#262626",
      "#0d0d0d",
    ],
    "grey-bg": [
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
      "#f7f8fa",
    ],
    purple: [
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
      "#ae089e",
    ],
  },
  fontFamily: "Inter, sans-serif",
  fontFamilyMonospace: "Roboto Mono, Monospace",
  fontSizes: {
    xxs: "12px",
    xs: "13px",
    sm: "14px",
    md: "15px",
    lg: "17px",
    xl: "19px",
    xxl: "21px",
    title: "23px",
  },
  spacing: {
    xxs: "4px",
    xs: "8px",
    sm: "10px",
    md: "16px",
    lg: "24px",
    xl: "30px",
    xxl: "40px",
  },
  radius: {
    xs: "2px",
    sm: "5px",
    md: "8px",
    lg: "11px",
    xl: "14px",
  },
  headings: {
    sizes: {
      h1: { fontSize: "32px" },
      h2: { fontSize: "28px" },
      h3: { fontSize: "24px" },
      h4: { fontSize: "20px" },
      h5: { fontSize: "16px" },
    },
  },

  components: {
    Menu: {
      styles: (theme: MantineTheme) => ({
        label: { fontSize: theme.fontSizes.md, fontWeight: 500 },
      }),
      defaultProps: {
        size: "xs",
      },
    },
    Modal: {
      styles: (theme: MantineTheme) => ({
        title: { fontSize: theme.fontSizes.lg, fontWeight: 500 },
        content: { padding: "6px" },
      }),
      defaultProps: { lockScroll: false },
    },
    Button: {
      styles: (theme: MantineTheme) => ({
        label: { fontSize: theme.fontSizes.md, fontWeight: 400 },
      }),
      defaultProps: {
        fz: "md",
      },
    },
    Badge: {
      styles: (theme: MantineTheme) => ({
        root: { backgroundColor: theme.colors.gray["3"], color: "black" },
      }),
      defaultProps: {
        fz: "xs",
        fw: 400,
      },
    },
    Select: {
      styles: (theme: MantineTheme) => ({
        input: { fontSize: theme.fontSizes.md },
        root: { fontSize: theme.fontSizes.md },
        item: {
          fontSize: theme.fontSizes.md,
          "&[data-selected]": {
            backgroundColor: theme.colors["button-blue"][5],
            ":hover": {
              backgroundColor: theme.colors["button-blue"][5],
            },
          },
        },
      }),
    },
    InputWrapper: {
      styles: (theme: MantineTheme) => ({
        label: {
          fontSize: theme.fontSizes.md,
          color: theme.colors.dark,
          fontWeight: 500,
          marginBottom: "4px",
        },
        description: {
          fontSize: theme.fontSizes.md,
          color: theme.colors.gray[6],
          marginBottom: "5px",
        },
      }),
    },
  },

  globalStyles: (theme: MantineTheme) => ({
    "input[type=text]": { fontSize: theme.fontSizes.md },
    ".mantine-Textarea-input": { fontSize: theme.fontSizes.md },
    ".mantine-Alert-message": { fontSize: theme.fontSizes.md },
    ".layout-container": {
      minWidth: "max(74rem, 100%)",
    },
    ".layout-container-inner": {
      minWidth: "64rem",
      paddingLeft: "0",
      paddingRight: "0",
    },
  }),
} as MantineThemeOverride;

export default customMantineTheme;
